# Generated by Django 5.2.7 on 2025-10-14 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteHidrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REUSO', 'Reúso de aguas tratadas'), ('DESALACION', 'Desalación modular'), ('RECARGA', 'Recarga de acuíferos'), ('TELEMETRIA', 'Telemetría y control de extracciones'), ('OTRA', 'Otra solución')], max_length=20)),
                ('capacidad_m3d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energia_renovable', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('objetivo', models.TextField()),
                ('avance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sequia.fuentehidrica')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequia.region')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('volumen_reutilizado_m3d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perdidas_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nivel_freatico_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('caudal_ecologico_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='sequia.medida')),
            ],
        ),
    ]
