# Generated by Django 5.2.7 on 2025-10-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nombre']},
        ),
    ]
