from typing import Protocol, Iterable, Dict, Any

class ISequiaRepository(Protocol):
    def regiones(self) -> Iterable[Dict[str, Any]]: ...
    def crear_medida(self, **data) -> Dict[str, Any]: ...
    def listar_medidas(self) -> Iterable[Dict[str, Any]]: ...
    def obtener_medida(self, pk: int) -> Dict[str, Any]: ...
    def actualizar_medida(self, pk: int, **data) -> Dict[str, Any]: ...
    def eliminar_medida(self, pk: int) -> None: ...
